{{- if not .Values.config.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "electrolux-websocket2mqtt.configSecretName" . }}
  labels:
    {{- include "electrolux-websocket2mqtt.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.config.configFilename }}: |
    {{ .Values.config.configBody | indent 4 }}
{{- end }}