---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "electrolux-websocket2mqtt.fullname" . }}
  labels:
    {{- include "electrolux-websocket2mqtt.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "electrolux-websocket2mqtt.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "electrolux-websocket2mqtt.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "electrolux-websocket2mqtt.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: daemon
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "electrolux-websocket2mqtt"
            - "--cfg"
            - "{{ .Values.config.configDir }}/{{ .Values.config.configFilename }}"
            - "daemon"
          env: []
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: {{ .Values.config.configDir }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "electrolux-websocket2mqtt.configSecretName" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}